// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsQH3mzMglOFrzxFUE-uNOtNiH4pgaoqs',
    appId: '1:153229865253:web:792897fccad6e1b1b5aacc',
    messagingSenderId: '153229865253',
    projectId: 'ohnoteapp',
    authDomain: 'ohnoteapp.firebaseapp.com',
    storageBucket: 'ohnoteapp.firebasestorage.app',
    measurementId: 'G-L7LSW0GFXS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApr-5iA8XJQEYqMKn88Mvh2rTqbaznlc8',
    appId: '1:153229865253:android:69f30098341e3433b5aacc',
    messagingSenderId: '153229865253',
    projectId: 'ohnoteapp',
    storageBucket: 'ohnoteapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgQuWznE1VkAc3gZGPmUs7Y2r-lwuI0eg',
    appId: '1:153229865253:ios:6b1242da7d3f7262b5aacc',
    messagingSenderId: '153229865253',
    projectId: 'ohnoteapp',
    storageBucket: 'ohnoteapp.firebasestorage.app',
    iosBundleId: 'com.trendsapps.ohnote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgQuWznE1VkAc3gZGPmUs7Y2r-lwuI0eg',
    appId: '1:153229865253:ios:6b1242da7d3f7262b5aacc',
    messagingSenderId: '153229865253',
    projectId: 'ohnoteapp',
    storageBucket: 'ohnoteapp.firebasestorage.app',
    iosBundleId: 'com.trendsapps.ohnote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsQH3mzMglOFrzxFUE-uNOtNiH4pgaoqs',
    appId: '1:153229865253:web:7aa95b7ff439cc35b5aacc',
    messagingSenderId: '153229865253',
    projectId: 'ohnoteapp',
    authDomain: 'ohnoteapp.firebaseapp.com',
    storageBucket: 'ohnoteapp.firebasestorage.app',
    measurementId: 'G-QWG0XFMXYZ',
  );
}
